function T = empty_iid_events_table(tz)
% Correctly-typed 0-row template for iid_events.csv. Single source of
% truth shared by run_pipeline_edf.m (writer) and read_pipeline_csv.m
% (reader) -- keep both in sync with this file.
    T = table('Size', [0 16], ...
        'VariableTypes', {'cell', 'cell', 'datetime', 'cell', 'double', 'double', 'double', 'datetime', 'datetime', ...
        'double', 'double', 'cell', 'double', 'double', 'logical', 'double'}, ...
        'VariableNames', {'subject_id', 'region', 'session_start', 'source_file', 'complex_id', 'start_s', 'end_s', ...
        'start_abs', 'end_abs', 'duration_ms', 'n_spikes', 'classification', 'max_amplitude_mV', 'mean_amplitude_mV', ...
        'in_burst', 'burst_id'});
    T = apply_tz(T, tz);
end
