function names = qc_column_names()
% QC_COLUMN_NAMES  Column list for qc_report.csv. Single source of truth
% shared by run_pipeline_edf.m (build_qc_row, writer) and
% read_pipeline_csv.m / empty_qc_table.m (reader) -- keep both in sync
% with this file.
    names = {'subject_id', 'region', 'source_file', 'session_start', 'stages_completed', ...
        'n_errors', 'error_messages', 'n_blocks_rejected_short', 'outlier_pct', 'nan_pct', 'n_warnings', 'warning_messages', ...
        'case_applied', 'case_source', 'suggested_case', 'quality_class', ...
        'sigma_band_uV', 'reference_used', 'reference_source', 'gain_estimate_raw', ...
        'gain_applied', 'gain_source', 'sensitivity_equivalent_uV_per_mm', ...
        'line_ratio_db', 'line_ratio_p95_db', 'line_ratio_max_db', 'pct_time_line_high', ...
        'notch_applied', 'quantization_step_uV', 'snr_quantization_db', 'adc_codes_span', ...
        'pct_clipped', 'flat_fraction', 'notch_blocks_skipped', 'seizure_threshold_mode', 'iid_threshold_mode'};
end
